# Matrix 

matrix[row,col]

In [1]:
sales_us = [2345,3434,4545,4345]
sales_apac = [3456,6578,7787,6767]
sales_jp = [5678,4444,5454,3333]

In [2]:
import numpy as np

In [3]:
sales_matrix = np.array([sales_us,sales_apac,sales_jp])

In [4]:
sales_matrix

array([[2345, 3434, 4545, 4345],
       [3456, 6578, 7787, 6767],
       [5678, 4444, 5454, 3333]])

In [5]:
profit_us = [123,456,456,567]
profit_apac = [345,545,656,434]
profit_jp = [345,878,666,543]

In [8]:
profit_matrix = np.array([profit_us,profit_apac,profit_jp])

In [9]:
profit_matrix

array([[123, 456, 456, 567],
       [345, 545, 656, 434],
       [345, 878, 666, 543]])

In [10]:
profit_matrix/sales_matrix

array([[0.05245203, 0.13278975, 0.10033003, 0.13049482],
       [0.09982639, 0.08285193, 0.08424297, 0.06413477],
       [0.06076083, 0.19756976, 0.12211221, 0.16291629]])

In [11]:
quarter = ['Q1','Q2','Q3','Q4']
region = ['US','APAC','JP']

In [13]:
qdict = {'Q1':0, 'Q2':1, 'Q3':2, 'Q4':3}
rdict = {'US':0,'APAC':1,'JP':2}

In [15]:
sales_matrix[rdict['JP']][qdict['Q3']]

5454

In [17]:
sales_matrix[rdict['APAC']][qdict["Q3"]]

7787

# DataFrames

* It is a table in python
    * It is a 2-D Object
    * Rows and Columns 

We will use Pandas to use dataframes

we will create a dictionary to make a dataframe

In [18]:
import pandas as pd

In [44]:
raw_data={'cust_id':[1,2,3,4,5,6],
         'First Name':['Alex','John','Mathew','James','Alister','Rahul'],
         'Last Name':['Cook','Warne','Hayen','Anderson','Cook','Tiwari']}

In [45]:
customer_details = pd.DataFrame(raw_data)

In [46]:
customer_details

cust_id First Name Last Name
0        1       Alex      Cook
1        2       John     Warne
2        3     Mathew     Hayen
3        4      James  Anderson
4        5    Alister      Cook
5        6      Rahul    Tiwari

In [42]:
raw_data1 = {'c_id':[1,2,3,4,5,7],
            'Sales':[123,323,333,443,332,344],
            'product':['TV','TV','AC','MW','FR','MW']}

In [43]:
sales_details = pd.DataFrame(raw_data1)

In [33]:
sales_details

c_id  Sales product
0     1    123      TV
1     2    323      TV
2     3    333      AC
3     4    443      MW
4     5    332      FR
5     7    344      MW

# Joins

### Inner Join: Joining common records in both tables 
### Left Outer Join: All the records from left and all the matching records from rigth 
### Right Outer Join: All the records from right and all the matching records from left
### Outer Join: All the records from both the tables participate 

In [47]:
#Common details 
pd.merge(customer_details,sales_details,left_on='cust_id',right_on='c_id',how='inner')

cust_id First Name Last Name  c_id  Sales product
0        1       Alex      Cook     1    123      TV
1        2       John     Warne     2    323      TV
2        3     Mathew     Hayen     3    333      AC
3        4      James  Anderson     4    443      MW
4        5    Alister      Cook     5    332      FR

In [48]:
#All left + right common
pd.merge(customer_details,sales_details,left_on='cust_id',right_on='c_id',how='left')

cust_id First Name Last Name  c_id  Sales product
0        1       Alex      Cook   1.0  123.0      TV
1        2       John     Warne   2.0  323.0      TV
2        3     Mathew     Hayen   3.0  333.0      AC
3        4      James  Anderson   4.0  443.0      MW
4        5    Alister      Cook   5.0  332.0      FR
5        6      Rahul    Tiwari   NaN    NaN     NaN

In [49]:
#All right + common left
pd.merge(customer_details,sales_details,left_on='cust_id',right_on='c_id',how='right')

cust_id First Name Last Name  c_id  Sales product
0      1.0       Alex      Cook     1    123      TV
1      2.0       John     Warne     2    323      TV
2      3.0     Mathew     Hayen     3    333      AC
3      4.0      James  Anderson     4    443      MW
4      5.0    Alister      Cook     5    332      FR
5      NaN        NaN       NaN     7    344      MW

In [53]:
#Everything 
pd.merge(customer_details,sales_details,left_on='cust_id',right_on='c_id',how='outer')

cust_id First Name Last Name  c_id  Sales product
0      1.0       Alex      Cook   1.0  123.0      TV
1      2.0       John     Warne   2.0  323.0      TV
2      3.0     Mathew     Hayen   3.0  333.0      AC
3      4.0      James  Anderson   4.0  443.0      MW
4      5.0    Alister      Cook   5.0  332.0      FR
5      6.0      Rahul    Tiwari   NaN    NaN     NaN
6      NaN        NaN       NaN   7.0  344.0      MW

In [54]:
#Joining based on row, this is called INDEX join
pd.concat([customer_details,sales_details],axis=1)

cust_id First Name Last Name  c_id  Sales product
0        1       Alex      Cook     1    123      TV
1        2       John     Warne     2    323      TV
2        3     Mathew     Hayen     3    333      AC
3        4      James  Anderson     4    443      MW
4        5    Alister      Cook     5    332      FR
5        6      Rahul    Tiwari     7    344      MW

In [56]:
#Appending 2 tables together 
pd.concat([customer_details,sales_details],axis=0)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


First Name Last Name  Sales  c_id  cust_id product
0       Alex      Cook    NaN   NaN      1.0     NaN
1       John     Warne    NaN   NaN      2.0     NaN
2     Mathew     Hayen    NaN   NaN      3.0     NaN
3      James  Anderson    NaN   NaN      4.0     NaN
4    Alister      Cook    NaN   NaN      5.0     NaN
5      Rahul    Tiwari    NaN   NaN      6.0     NaN
0        NaN       NaN  123.0   1.0      NaN      TV
1        NaN       NaN  323.0   2.0      NaN      TV
2        NaN       NaN  333.0   3.0      NaN      AC
3        NaN       NaN  443.0   4.0      NaN      MW
4        NaN       NaN  332.0   5.0      NaN      FR
5        NaN       NaN  344.0   7.0      NaN      MW

In [ ]:
# Importing .csv in python

pd.read_csv('FileName or FilePath')

In [57]:
#It gives you ability to get paths and working directory 
import os
os.getcwd()

'/Users/saihajpreet/OneDrive/MacBook Pro/Data Science Python'

In [ ]:
# Used to change directories 
od.chdir()

In [ ]:
#Union All 
pd.concat([DF1,DF2], axis=0)

#Union
pd.concat([DF1,DF2],axis=0).drop_duplicates()

In [ ]:
#Top 6 records 
tips.head(6)

In [ ]:
#This will get data from somefile called "tips", it will print mentioned columns from that file 
#Head command will print the number of resposnes you want it to print 

tips[['total_bills','tip','smoker','time']].head(5)

In [ ]:
#Want time to be dinner and need top 5 records
tips[tips['time']=='Dinner'].head(5)

In [ ]:
#Want time to be dinner and tip >5
tips[(tips['time']=='Dinner')&(tips['tips']>5)]

In [ ]:
#Want size>=5 or total_bill>45
tips[(tips['size']>='5')|(tips['total_bill']>45)]

In [ ]:
#Want to groupby 'sex'
tips.groupby('sex').size()

#prints the count of each column
tips.groupby('sex').count()

In [ ]:
#want to group by smoker and day. We want the count and average  

tips.groupby(['smoker','day']).agg({'tip':[np.size, np.mean]})

### Matplotlib.pyplot and seaborn for visualization