In [ ]:
#Doubts - How to convert index to column again 
         #How can we do minus in Python 

In [1]:
import os
os.chdir('D:\\Trainings\\R and Python Classes\\Machine Learning A-Z\\Part 2 - Regression\\Section 4 - Simple Linear Regression\\Simple_Linear_Regression\\Simple_Linear_Regression\\')

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv('Salary_Data.csv')

In [4]:
dataset

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [5]:
x = dataset.iloc[:,:-1].values

In [6]:
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [7]:
y = dataset.iloc[:,1].values

In [8]:
y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [12]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [13]:
regressor.coef_

array([9777.4814563])

In [14]:
regressor.intercept_

22589.176065993568

In [ ]:
Salary = 9777.48 * Exp + 22589.17

In [15]:
y_pred = regressor.predict(x_test)

In [16]:
y_pred

array([92009.29440573, 33344.40566792, 53877.11672616, 99831.27957077,
       74409.82778439, 35299.90195918])

In [17]:
y_test

array([ 98273.,  39343.,  64445., 101302.,  83088.,  46205.])

In [18]:
x_test

array([[7.1],
       [1.1],
       [3.2],
       [7.9],
       [5.3],
       [1.3]])

In [19]:
from sklearn.metrics import r2_score

In [20]:
r2_score(y_test,y_pred)

0.8892439906396428

In [21]:
dataset_new = pd.read_excel('prediction_new.xlsx')

In [22]:
x_new = dataset_new.iloc[:].values

In [24]:
y_pred_new = regressor.predict(x_new)

In [25]:
y_pred_new

array([149696.4349979 , 159473.9164542 , 169251.39791051, 179028.87936681,
        22589.17606599])

In [ ]:
#Multiple Linear Regression

In [26]:
os.chdir('D:\\Trainings\\R and Python Classes\\Machine Learning A-Z\\Part 2 - Regression\\Section 5 - Multiple Linear Regression\\Multiple_Linear_Regression\\Multiple_Linear_Regression\\')

In [27]:
dataset = pd.read_csv('50_Startups.csv')

In [28]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [29]:
x = dataset.iloc[:,:-1].values

In [30]:
y = dataset.iloc[:,4].values

In [31]:
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [32]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [34]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder = LabelEncoder()
x[:,3]=labelencoder.fit_transform(x[:,3])
onehotencoder = OneHotEncoder(categorical_features=[3])
x = onehotencoder.fit_transform(x).toarray()

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [36]:
pd.DataFrame(x)

0    1    2          3          4          5
0   0.0  0.0  1.0  165349.20  136897.80  471784.10
1   1.0  0.0  0.0  162597.70  151377.59  443898.53
2   0.0  1.0  0.0  153441.51  101145.55  407934.54
3   0.0  0.0  1.0  144372.41  118671.85  383199.62
4   0.0  1.0  0.0  142107.34   91391.77  366168.42
5   0.0  0.0  1.0  131876.90   99814.71  362861.36
6   1.0  0.0  0.0  134615.46  147198.87  127716.82
7   0.0  1.0  0.0  130298.13  145530.06  323876.68
8   0.0  0.0  1.0  120542.52  148718.95  311613.29
9   1.0  0.0  0.0  123334.88  108679.17  304981.62
10  0.0  1.0  0.0  101913.08  110594.11  229160.95
11  1.0  0.0  0.0  100671.96   91790.61  249744.55
12  0.0  1.0  0.0   93863.75  127320.38  249839.44
13  1.0  0.0  0.0   91992.39  135495.07  252664.93
14  0.0  1.0  0.0  119943.24  156547.42  256512.92
15  0.0  0.0  1.0  114523.61  122616.84  261776.23
16  1.0  0.0  0.0   78013.11  121597.55  264346.06
17  0.0  0.0  1.0   94657.16  145077.58  282574.31
18  0.0  1.0  0.0   91749.16  114175.79  294919.57
19  0.0  0.0  1.0   86419.70  153514.11       0.00
20  1.0  0.0  0.0   76253.86  113867.30  298664.47
21  0.0  0.0  1.0   78389.47  153773.43  299737.29
22  0.0  1.0  0.0   73994.56  122782.75  303319.26
23  0.0  1.0  0.0   67532.53  105751.03  304768.73
24  0.0  0.0  1.0   77044.01   99281.34  140574.81
25  1.0  0.0  0.0   64664.71  139553.16  137962.62
26  0.0  1.0  0.0   75328.87  144135.98  134050.07
27  0.0  0.0  1.0   72107.60  127864.55  353183.81
28  0.0  1.0  0.0   66051.52  182645.56  118148.20
29  0.0  0.0  1.0   65605.48  153032.06  107138.38
30  0.0  1.0  0.0   61994.48  115641.28   91131.24
31  0.0  0.0  1.0   61136.38  152701.92   88218.23
32  1.0  0.0  0.0   63408.86  129219.61   46085.25
33  0.0  1.0  0.0   55493.95  103057.49  214634.81
34  1.0  0.0  0.0   46426.07  157693.92  210797.67
35  0.0  0.0  1.0   46014.02   85047.44  205517.64
36  0.0  1.0  0.0   28663.76  127056.21  201126.82
37  1.0  0.0  0.0   44069.95   51283.14  197029.42
38  0.0  0.0  1.0   20229.59   65947.93  185265.10
39  1.0  0.0  0.0   38558.51   82982.09  174999.30
40  1.0  0.0  0.0   28754.33  118546.05  172795.67
41  0.0  1.0  0.0   27892.92   84710.77  164470.71
42  1.0  0.0  0.0   23640.93   96189.63  148001.11
43  0.0  0.0  1.0   15505.73  127382.30   35534.17
44  1.0  0.0  0.0   22177.74  154806.14   28334.72
45  0.0  0.0  1.0    1000.23  124153.04    1903.93
46  0.0  1.0  0.0    1315.46  115816.21  297114.46
47  1.0  0.0  0.0       0.00  135426.92       0.00
48  0.0  0.0  1.0     542.05   51743.15       0.00
49  1.0  0.0  0.0       0.00  116983.80   45173.06

In [37]:
x = x[:,1:]

In [39]:
pd.DataFrame(x)

0    1          2          3          4
0   0.0  1.0  165349.20  136897.80  471784.10
1   0.0  0.0  162597.70  151377.59  443898.53
2   1.0  0.0  153441.51  101145.55  407934.54
3   0.0  1.0  144372.41  118671.85  383199.62
4   1.0  0.0  142107.34   91391.77  366168.42
5   0.0  1.0  131876.90   99814.71  362861.36
6   0.0  0.0  134615.46  147198.87  127716.82
7   1.0  0.0  130298.13  145530.06  323876.68
8   0.0  1.0  120542.52  148718.95  311613.29
9   0.0  0.0  123334.88  108679.17  304981.62
10  1.0  0.0  101913.08  110594.11  229160.95
11  0.0  0.0  100671.96   91790.61  249744.55
12  1.0  0.0   93863.75  127320.38  249839.44
13  0.0  0.0   91992.39  135495.07  252664.93
14  1.0  0.0  119943.24  156547.42  256512.92
15  0.0  1.0  114523.61  122616.84  261776.23
16  0.0  0.0   78013.11  121597.55  264346.06
17  0.0  1.0   94657.16  145077.58  282574.31
18  1.0  0.0   91749.16  114175.79  294919.57
19  0.0  1.0   86419.70  153514.11       0.00
20  0.0  0.0   76253.86  113867.30  298664.47
21  0.0  1.0   78389.47  153773.43  299737.29
22  1.0  0.0   73994.56  122782.75  303319.26
23  1.0  0.0   67532.53  105751.03  304768.73
24  0.0  1.0   77044.01   99281.34  140574.81
25  0.0  0.0   64664.71  139553.16  137962.62
26  1.0  0.0   75328.87  144135.98  134050.07
27  0.0  1.0   72107.60  127864.55  353183.81
28  1.0  0.0   66051.52  182645.56  118148.20
29  0.0  1.0   65605.48  153032.06  107138.38
30  1.0  0.0   61994.48  115641.28   91131.24
31  0.0  1.0   61136.38  152701.92   88218.23
32  0.0  0.0   63408.86  129219.61   46085.25
33  1.0  0.0   55493.95  103057.49  214634.81
34  0.0  0.0   46426.07  157693.92  210797.67
35  0.0  1.0   46014.02   85047.44  205517.64
36  1.0  0.0   28663.76  127056.21  201126.82
37  0.0  0.0   44069.95   51283.14  197029.42
38  0.0  1.0   20229.59   65947.93  185265.10
39  0.0  0.0   38558.51   82982.09  174999.30
40  0.0  0.0   28754.33  118546.05  172795.67
41  1.0  0.0   27892.92   84710.77  164470.71
42  0.0  0.0   23640.93   96189.63  148001.11
43  0.0  1.0   15505.73  127382.30   35534.17
44  0.0  0.0   22177.74  154806.14   28334.72
45  0.0  1.0    1000.23  124153.04    1903.93
46  1.0  0.0    1315.46  115816.21  297114.46
47  0.0  0.0       0.00  135426.92       0.00
48  0.0  1.0     542.05   51743.15       0.00
49  0.0  0.0       0.00  116983.80   45173.06

In [40]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [41]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [42]:
regressor.coef_

array([ 1.19024869e+03,  8.94905282e+02,  8.08380582e-01, -2.52123419e-02,
        2.74861779e-02])

In [43]:
regressor.intercept_

49016.12449676858

In [44]:
from sklearn.metrics import r2_score

In [45]:
y_pred = regressor.predict(x_test)

In [46]:
r2_score(y_test,y_pred)

0.9812496804098026

In [47]:
import statsmodels.formula.api as sm

In [49]:
import numpy as np

In [50]:
x = np.append(arr=x, values=np.ones((50,1)).astype(int), axis=1)

In [51]:
pd.DataFrame(x)

0    1          2          3          4    5
0   0.0  1.0  165349.20  136897.80  471784.10  1.0
1   0.0  0.0  162597.70  151377.59  443898.53  1.0
2   1.0  0.0  153441.51  101145.55  407934.54  1.0
3   0.0  1.0  144372.41  118671.85  383199.62  1.0
4   1.0  0.0  142107.34   91391.77  366168.42  1.0
5   0.0  1.0  131876.90   99814.71  362861.36  1.0
6   0.0  0.0  134615.46  147198.87  127716.82  1.0
7   1.0  0.0  130298.13  145530.06  323876.68  1.0
8   0.0  1.0  120542.52  148718.95  311613.29  1.0
9   0.0  0.0  123334.88  108679.17  304981.62  1.0
10  1.0  0.0  101913.08  110594.11  229160.95  1.0
11  0.0  0.0  100671.96   91790.61  249744.55  1.0
12  1.0  0.0   93863.75  127320.38  249839.44  1.0
13  0.0  0.0   91992.39  135495.07  252664.93  1.0
14  1.0  0.0  119943.24  156547.42  256512.92  1.0
15  0.0  1.0  114523.61  122616.84  261776.23  1.0
16  0.0  0.0   78013.11  121597.55  264346.06  1.0
17  0.0  1.0   94657.16  145077.58  282574.31  1.0
18  1.0  0.0   91749.16  114175.79  294919.57  1.0
19  0.0  1.0   86419.70  153514.11       0.00  1.0
20  0.0  0.0   76253.86  113867.30  298664.47  1.0
21  0.0  1.0   78389.47  153773.43  299737.29  1.0
22  1.0  0.0   73994.56  122782.75  303319.26  1.0
23  1.0  0.0   67532.53  105751.03  304768.73  1.0
24  0.0  1.0   77044.01   99281.34  140574.81  1.0
25  0.0  0.0   64664.71  139553.16  137962.62  1.0
26  1.0  0.0   75328.87  144135.98  134050.07  1.0
27  0.0  1.0   72107.60  127864.55  353183.81  1.0
28  1.0  0.0   66051.52  182645.56  118148.20  1.0
29  0.0  1.0   65605.48  153032.06  107138.38  1.0
30  1.0  0.0   61994.48  115641.28   91131.24  1.0
31  0.0  1.0   61136.38  152701.92   88218.23  1.0
32  0.0  0.0   63408.86  129219.61   46085.25  1.0
33  1.0  0.0   55493.95  103057.49  214634.81  1.0
34  0.0  0.0   46426.07  157693.92  210797.67  1.0
35  0.0  1.0   46014.02   85047.44  205517.64  1.0
36  1.0  0.0   28663.76  127056.21  201126.82  1.0
37  0.0  0.0   44069.95   51283.14  197029.42  1.0
38  0.0  1.0   20229.59   65947.93  185265.10  1.0
39  0.0  0.0   38558.51   82982.09  174999.30  1.0
40  0.0  0.0   28754.33  118546.05  172795.67  1.0
41  1.0  0.0   27892.92   84710.77  164470.71  1.0
42  0.0  0.0   23640.93   96189.63  148001.11  1.0
43  0.0  1.0   15505.73  127382.30   35534.17  1.0
44  0.0  0.0   22177.74  154806.14   28334.72  1.0
45  0.0  1.0    1000.23  124153.04    1903.93  1.0
46  1.0  0.0    1315.46  115816.21  297114.46  1.0
47  0.0  0.0       0.00  135426.92       0.00  1.0
48  0.0  1.0     542.05   51743.15       0.00  1.0
49  0.0  0.0       0.00  116983.80   45173.06  1.0

In [52]:
regressor_ols = sm.OLS(endog=y, exog=x).fit()

In [53]:
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Sat, 22 Jun 2019   Prob (F-statistic):           1.34e-27
Time:                        22:32:59   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           198.7888   3371.007      0.059      0.953   -6595.030    6992.607
x2           -41.8870   3256.039     -0.013      0.990   -6604.003    6520.229
x3             0.8060      0.046     17.369      0.000       0.712       0.900
x4            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x5             0.0270      0.017      1.574      0.123      -0.008       0.062
const       5.013e+04   6884.820      7.281      0.000    3.62e+04     6.4e+04
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.45e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""